/*
 * SPDX-FileCopyrightText: 2024-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#define ESP_UTILS_CONF_CHECK_HANDLE_METHOD (ESP_UTILS_CHECK_HANDLE_WITH_ERROR_LOG)

#define ESP_UTILS_CONF_LOG_LEVEL (ESP_UTILS_LOG_LEVEL_INFO)
#if ESP_UTILS_CONF_LOG_LEVEL == ESP_UTILS_LOG_LEVEL_DEBUG

#define ESP_UTILS_CONF_ENABLE_LOG_TRACE (0)

#endif  // ESP_UTILS_CONF_LOG_LEVEL

#define ESP_UTILS_CONF_MEM_GEN_ALLOC_DEFAULT_ENABLE (1)


#define ESP_UTILS_CONF_MEM_GEN_ALLOC_TYPE (ESP_UTILS_MEM_ALLOC_TYPE_STDLIB)
#if ESP_UTILS_CONF_MEM_GEN_ALLOC_TYPE == ESP_UTILS_MEM_ALLOC_TYPE_ESP

#define ESP_UTILS_CONF_MEM_GEN_ALLOC_ESP_ALIGN (1)
#define ESP_UTILS_CONF_MEM_GEN_ALLOC_ESP_CAPS (MALLOC_CAP_DEFAULT | MALLOC_CAP_8BIT)

#elif ESP_UTILS_CONF_MEM_GEN_ALLOC_TYPE == ESP_UTILS_MEM_ALLOC_TYPE_CUSTOM

#define ESP_UTILS_CONF_MEM_GEN_ALLOC_CUSTOM_INCLUDE "stdlib.h"
#define ESP_UTILS_CONF_MEM_GEN_ALLOC_CUSTOM_MALLOC malloc
#define ESP_UTILS_CONF_MEM_GEN_ALLOC_CUSTOM_FREE free

#endif  // ESP_UTILS_CONF_MEM_GEN_ALLOC_TYPE

#define ESP_UTILS_CONF_FILE_VERSION_MAJOR 1
#define ESP_UTILS_CONF_FILE_VERSION_MINOR 2
#define ESP_UTILS_CONF_FILE_VERSION_PATCH 0
